name: Deploy Django Backend

on:
  push:
    branches:
      - main  # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ubuntu
        SCRIPT_AFTER: |
          cd /home/ubuntu/backend
          git pull origin main
          pip install -r requirements.txt
          python manage.py migrate
          systemctl restart gunicorn